language: python
dist: focal
python:
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r requirements.txt
script:
  - cp monitor/settings.example.py monitor/settings.py
  - python3 manage.py check
  - python3 manage.py test -v 2
  - python3 manage.py migrate
