# Generated by Django 3.1.3 on 2021-09-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckConfig',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('location', models.CharField(default='none', max_length=128)),
                ('config', models.JSONField(max_length=1024)),
                ('flow', models.JSONField(default=dict, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('check_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('success', models.BooleanField()),
                ('resp_code', models.IntegerField(null=True)),
                ('timings', models.JSONField(default=list)),
                ('result', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='checkhistory',
            index=models.Index(fields=['-created_at'], name='checks_chec_created_c5f031_idx'),
        ),
        migrations.AddIndex(
            model_name='checkhistory',
            index=models.Index(fields=['check_id'], name='checks_chec_check_i_10b57c_idx'),
        ),
    ]
