version: "3"

services:
  mysql:
    image: library/percona:5.7-centos
    ports:
    - "3306:3306"
    environment:
      MYSQL_DATABASE: monitor
      MYSQL_USER: monitor
      MYSQL_PASSWORD: monitor
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - monitor
  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - "1025:1025"
    - "1080:1080"
    networks:
      - monitor
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#    - "5672:5672"
#    - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: rabbitmq
#      RABBITMQ_DEFAULT_PASS: rabbitmq
#      RABBITMQ_DEFAULT_VHOST: monitor
#    networks:
#      - monitor

networks:
  monitor:
    driver: bridge
